# Generated by Django 5.1.3 on 2024-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_queries', '0002_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='book_data', to='django_queries.genre'),
        ),
    ]
