# Generated by Django 5.1.3 on 2025-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
